//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPCuatrimestral_equipo_23A {

    public partial class PerfilRecepcionista {
        protected global::System.Web.UI.WebControls.Image imgAvatarGrande;
        protected global::System.Web.UI.WebControls.Label lblNombreCompletoTitulo;
        protected global::System.Web.UI.WebControls.Label lblRolTitulo;
        protected global::System.Web.UI.WebControls.Label lblIdUsuarioTitulo;
        protected global::System.Web.UI.WebControls.TextBox txtNombre;
        protected global::System.Web.UI.WebControls.TextBox txtApellido;
        protected global::System.Web.UI.WebControls.TextBox txtDni;
        protected global::System.Web.UI.WebControls.TextBox txtFechaNac;
        protected global::System.Web.UI.WebControls.TextBox txtTelefono;
        protected global::System.Web.UI.WebControls.TextBox txtDireccion;
        protected global::System.Web.UI.WebControls.Button btnGuardarInfoPersonal;
        protected global::System.Web.UI.WebControls.Label lblEmailLogin;
    }
}
